name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checout@v3
      - name: Install deps
        run: npm i
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: build-files
          path: build  
