name: Test
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
  lint:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint
  build:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Build App
        run: npm run build
