name: Test
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
      - name: Lint code
        run: npm run lint
      - name: Build App
        run: npm run build
