name: Deploy React App
on: push
jobs:
  test_app: 
    runs-on: windows-latest
    steps: 
       - name: Get the Repository code
         uses: actions/checkout@v3
       - name: Install dependencies
         run: npm ci
       - name: Test application
         run: npm run test    
  lint: 
    runs-on: windows-latest
    steps: 
        - name: Get the Repository code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Lint application
          run: npm run lint  
  build: 
    runs-on: windows-latest
    steps: 
        - name: Get the Repository code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build
        - name: Deploy
          run: echo Deploying...
        