name: Test
on: 
  push:
    branches:
      - 'main'
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test:
    strategy: 
      matrix: 
        node-vesrion: [14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-vesrion }}
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: C:/Users/Public
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
  lint:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: C:/Users/Public
          key: node-modules-${{ hashFiles('**/package-lock.json')}}  
      - name: Install deps
        run: npm install
      - name: Lint code
        run: npm run lint
  build:
    runs-on: windows-latest
    needs: [lint, test]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with: 
          path: C:/Users/Public
          key: node-modules-${{ hashFiles('**/package-lock.json')}}  
      - name: Install deps
        run: npm install
      - name: Build App
        run: npm run build
