name: Test
on: push
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test app
        run: npm run test
      - name: Lint code
        run: npm run lint
      - name: Build App
        run: npm run build
