name: Print Pull Request Context
on: [workflow_dispatch]
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print event of issue
        shell: pwsh
        run: echo "${{ toJSON(github) }}"

      