name: Test React App
on: push
jobs:
  print: 
    runs-on: windows-latest
    steps: 
       - name: Get the Repository code
         uses: actions/checkout@v3
       - name: Install dependencies
         run: npm ci
       - name: Test application
         run: npm run test    
